version: "3.7"
   
services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/
    ports:
<<<<<<< HEAD
      - '5433:5432'
=======
      - '5440:5432'
>>>>>>> 0e80b163243e2528e53a85aa689c67c56da1b044
    env_file: resume/.env

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: resume/.env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  pg_data: 