version: "3.7"
   
services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5439:5432'
    env_file: resume/.env

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: resume/.env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data: 
