version: 2.1
jobs:
  lint-app:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            
            echo "--------- The images is Building ------------"

            docker build -t resume ./resume
            docker tag resume paulmeric/resume:v1
            
            echo "-------- All images succesfully built----------"

            echo " ------- login in to hub--------"

            docker login -u paulmeric -p $DOCKERPASS

            echo "-------------- Pushing images to dockerhub-------"

            docker push paulmeric/resume:v1

workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]