version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py runserver
            echo " ------- login in to hub--------"
            docker login -u paulmeric -p $DOCKERPASS
            echo "-------------- Pushing images to dockerhub-------"
            docker push paulmeric/resume:v1
           
      - store_artifacts:
          path: test-reports/
          destination: python_app