apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-deployment
  labels:
    app: resume-backend

spec:
  replicas: 2
  selector:
    matchLabels:
      app: resume-backend
  template:
    metadata:
      labels:
        app: resume-backend
    spec:
      containers:
      - name: resume-backend
        image: paulmeric/resume-backend
        # imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: resume-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: resume-backend
    
