# Generated by Django 4.1.6 on 2023-02-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='Project')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': '4. Projects',
            },
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
