# Generated by Django 4.1.1 on 2022-09-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About', 'verbose_name_plural': '3. Abouts'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '11. Portfolios Categories'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Certificate', 'verbose_name_plural': '12. Certificates'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'ContactInfo', 'verbose_name_plural': '9. ContactInfos'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Education', 'verbose_name_plural': '6. Educations'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': 'Experience', 'verbose_name_plural': '7. Experiences'},
        ),
        migrations.AlterModelOptions(
            name='intro',
            options={'verbose_name': 'Intro', 'verbose_name_plural': '2. Intros'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['client'], 'verbose_name': 'Portfolio', 'verbose_name_plural': '12. Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': '1. Profiles'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': '4. Services'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Skill', 'verbose_name_plural': '8. Skills'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['name'], 'verbose_name': 'Testimonial', 'verbose_name_plural': '10. Testimonials'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_pics/default.png', null=True, upload_to='profile_pics/'),
        ),
    ]
